import type { Metadata } from "next";
import "./globals.css";
import LenisScroll from "./context/LenisScroll";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>blackpri0r.dev</title>
      <body className="font-offbit tracking-wider text-white">
        <LenisScroll>
          {children}
        </LenisScroll>
      </body>
    </html>
  );
}
